name: Mobile CD

on:
  push:
    branches:
      - main
    paths: [ 'mobile/**' ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: ðŸ— Checkout repo
      uses: actions/checkout@v3

    - name: ðŸ— Enable PNPM
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: ðŸ— Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: lts/*
        cache: pnpm

    - name: ðŸ— Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    # - name: ðŸ— Copy Google Services JSON key to /tmp
    #   run: echo "$GOOGLE_SERVICE_ACCOUNT" >> /tmp/key.json
    #   env:
    #     GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    - name: ðŸ“¦ Install dependencies
      run: pnpm i --no-frozen-lockfile

    - name: ðŸš€ Build app and release update
      run: |
        cd mobile
        eas build --auto-submit -p android --profile production --non-interactive --no-wait
